# .streamlit/secrets.toml MUST contain exactly:
ENCRYPTION_KEY = "8BvoQAgHsGfyboEKUN-x4kzi5jEnRFmrSQm-OMC_coQ="
ACCESS_HASH = "1140f61a6681a89a4752daf9a02db0a4c8bbbfc5509ad9aecdcc4b8ce52c1d24"  # <-- Your ACTUAL hash here